### PR TITLE
WIP - Add styled sections for lessons

### PR DESCRIPTION
**Pull request by robbiejaeger**
This PR adds styled lesson segments that you can add to your lessons.

There is a generic segment called a `lesson segment` that has a teal left border and box shadow. This can be used for turn and talks, “you do”, discussions, etc.

There is a specific segment for notes or things you want to really call out in a lesson. It has a yellow left border and yellow background.

Shout out to @ameseee for working on the initial styling of these segments.

Lastly, there is a segment that is used toward the end of the lesson for checks for understanding. It has a teal left border and teal background.

image

image

image

Within this PR, there is a lesson that is edited to use these segments, which is where these screenshots are from.

To add a segment, you have to add a `section` element with a class attribute of whatever segment you want to use, then write markdown as usual within the `section`. The only thing to note is that the markdown added in the `section` should not be indented.

### CODE REVIEW

**Comment by ameseee** [comment]
I think this looks great @robbiejaeger - do we have the go-ahead from Louisa to merge it in?

All the detail in the PR will be helpful in updating the README and making posters for instructors so it's a smooth roll out and implementation. 

To also note, the `h3` was used for the titles of a given box, and the class names available for use are:
- `.lesson-segment`
- `.checks-for-understanding`
- `.note`

**Comment by robbiejaeger** [comment]
I think this is GTM. I looked for places where adding the `parse_block_html: true` would break any of our existing markup, but I didn’t find anything. So we’ll just have to keep an eye out in case this creates some weird behavior in some of our markup.

**Comment by brittanystoroz** [comment]
I want this now so I am going to merge it THANK YOU FOR ALL OF YOUR HARD WORK ITS BEAUTIFUL

**Comment by brittanystoroz** [comment]
I added instructions to the README of this repo for how to create each box!

**Pull request merged**
